(lang dune 2.0)
(name ocaml-lib-in-rust)

(generate_opam_files true)

(package
 (name ocaml-lib-in-rust)
 (synopsis "FIXME:")
 (description "FIXME:")
 (depends
  (ocaml (>= "4.03.0"))
  (dune (>= "1.5"))
  conf-rust))
