(* Generated by ocaml-rs *)

open! Bigarray

(* file: lib.rs *)

type ob = {bids: int array; asks: float array}
external hello_world: unit -> int = "hello_world"
external get_orderbook: unit -> ob = "get_orderbook"
external spawn_worker: (int64, Bigarray.int64_elt, Bigarray.c_layout) Bigarray.Array1.t -> unit = "spawn_worker"
